cfg = {
"ufeatures": [
	{"name": "age", "cardinality": 6},
	{"name": "gender", "cardinality": 3},
	{"name": "marriageStatus", "cardinality": 13},
	{"name": "education", "cardinality": 8},
	{"name": "consumptionAbility", "cardinality": 3},
	{"name": "LBS", "cardinality": 863},
	{"name": "interest1", "cardinality": 122},
	{"name": "interest2", "cardinality": 80},
	{"name": "interest3", "cardinality": 10},
	{"name": "interest4", "cardinality": 10},
	{"name": "interest5", "cardinality": 136},
	{"name": "kw1", "cardinality": 263310},
	{"name": "kw2", "cardinality": 49778},
	{"name": "kw3", "cardinality": 12104},
	{"name": "topic1", "cardinality": 10000},
	{"name": "topic2", "cardinality": 9982},
	{"name": "topic3", "cardinality": 5920},
	{"name": "appIdInstall", "cardinality": 64858},
	{"name": "appIdAction", "cardinality": 6215},
	{"name": "ct", "cardinality": 5},
	{"name": "os", "cardinality": 3},
	{"name": "carrier", "cardinality": 4},
	{"name": "house", "cardinality":1},
],
"adfeatures": [
	{"name": "advertiserId", "cardinality": 79},
	{"name": "campaignId", "cardinality": 138},
	{"name": "creativeId", "cardinality": 173},
	{"name": "creativeSize", "cardinality": 15},
	{"name": "adCategoryId", "cardinality": 40},
	{"name": "productId", "cardinality": 33},
	{"name": "productType", "cardinality": 4},
]
}